### ISSUE TITLE
Diseñar el mockup de proyecto

### ISSUE THREAD

**Issue by VictorMtMwr** [ISCOUTB/AG-WeatherWhisper#2]

**Comment by BreynerPearson** [comment]
![Image](https://github.com/user-attachments/assets/b2049151-046e-45c7-98a6-34bdc4b810b2)

**Comment by BreynerPearson** [comment]
![Image](https://github.com/user-attachments/assets/897a3454-a7d1-403a-afd5-6611d985512a)

**Comment by BreynerPearson** [comment]
![Image](https://github.com/user-attachments/assets/0b8197f0-5c70-4ca6-a870-da3efb9295fe)

**Comment by BreynerPearson** [comment]
![Image](https://github.com/user-attachments/assets/1852da00-80e5-4db6-9f28-05baac73872a)

**Comment by BreynerPearson** [comment]
![Image](https://github.com/user-attachments/assets/9fcc9b68-fc9e-4f11-949c-eeb9005717e5)

**Comment by BreynerPearson** [comment]
![Image](https://github.com/user-attachments/assets/3f3c1719-78a7-466a-a479-44750b5005bb)
