### ISSUE TITLE
Revisar que tipo de bases de datos seleccionar (relacional o no relacional)

### ISSUE THREAD

**Issue by VictorMtMwr** [ISCOUTB/AG-WeatherWhisper#6]

**Comment by BreynerPearson** [comment]
Tipos de datos:

1. RELACIONALES (PostgreSQL)
Numéricos: Temperatura, humedad, velocidad del viento, presión atmosférica, etc.
Categóricos: tipo de clima ( soleado, lluvioso, nublado, etc.) tipo de precipitación( lluvia, nieve, granizo, etc.).
Geográficos: Coordenadas, geográficas (latitud, longitud, altitud), direcciones de viento, etc. 

2. NO RELACIONALES (MongoDB)
Imágenes y videos: Imágenes de satélite, Componentes visuales de las sugerencias, etc. Estos tipos de datos son no estructurados y pueden almacenarse en soluciones de almacenamiento de objetos.
Texto no estructurado: Comentarios de usuarios, informes del clima, etc. Estos tipos de datos son no estructurados y pueden almacenarse en base de datos NoSQL.

**Comment by jairoserrano** [comment]
adelante
