### ISSUE TITLE
Diseñar los componetes visuales de las sugerencias

### ISSUE THREAD

**Issue by VictorMtMwr** [ISCOUTB/AG-WeatherWhisper#7]

**Comment by juancho15dx** [comment]
A continuación, se emplea los siguientes componentes visuales intuitivos que representan las sugerencias de vestimenta segun las condiciones climáticas
![WhatsApp Image 2024-09-28 at 7 33 37 PM (1)](https://github.com/user-attachments/assets/b8c1e0fb-0912-4318-ba32-6dfd9ff28b35)
![WhatsApp Image 2024-09-28 at 7 33 37 PM](https://github.com/user-attachments/assets/c2a57f31-7856-42f9-b61f-92e9dce6de07)
![WhatsApp Image 2024-09-28 at 7 33 36 PM](https://github.com/user-attachments/assets/1f89dd12-56f7-48aa-81e0-612bb7a5cdcb)

**Comment by juancho15dx** [comment]
A continuación el diseño empleado cuenta con un esquema limpio e intuitivo que servirá![Image](https://github.com/user-attachments/assets/29770a70-9579-497c-9600-e87bf7748a28)
![Image](https://github.com/user-attachments/assets/bb19049b-b637-48bb-b35f-9df37163f30e)
![Image](https://github.com/user-attachments/assets/eb6c7b6e-a6d2-4dce-9145-81ac190be36a)
 para las sugerencias en las vestimenta para los usuarios

**Comment by juancho15dx** [comment]
Componentes visuales para cada sugerencia climática(Soleado, lluvioso,  bajas temperaturas, temperaturas templadas)

![Image](https://github.com/user-attachments/assets/135878f9-d41b-44d0-901c-6c6226e256dd)
![Image](https://github.com/user-attachments/assets/907af96e-20fe-4fd3-ad37-3e438d5b7ae8)
![Image](https://github.com/user-attachments/assets/b10e4f78-95d3-4dfe-bd28-985e0c08d185)
![Image](https://github.com/user-attachments/assets/0bbf93a0-4838-4fbc-b35a-1f3a61eebded)
