### ISSUE TITLE
Esquema de la API

### ISSUE THREAD

**Issue by VictorMtMwr** [ISCOUTB/AG-WeatherWhisper#9]

**Comment by VictorMtMwr** [comment]
![Image](https://github.com/user-attachments/assets/c7761d2b-8810-4eb1-a935-f3ef8fee4ff2)

**Comment by jairoserrano** [comment]
https://editor.swagger.io/

**Comment by VictorMtMwr** [comment]
openapi: 3.0.0
info:
  title: API de Recomendación de Ropa
  description: Una API que recomienda el tipo de ropa adecuado basado en la temperatura actual de una ciudad.
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Servidor local

paths:
  /recomendacion:
    get:
      summary: Obtener recomendación de ropa
      description: Devuelve una recomendación de ropa según la temperatura de una ciudad especificada.
      parameters:
        - name: ciudad
          in: query
          description: Nombre de la ciudad para obtener la temperatura.
          required: true
          schema:
            type: string
            example: Cartagena
      responses:
        '200':
          description: Recomendación de ropa basada en la temperatura
          content:
            application/json:
              schema:
                type: object
                properties:
                  ciudad:
                    type: string
                    description: Nombre de la ciudad.
                    example: Cartagena
                  temperatura:
                    type: number
                    format: float
                    description: Temperatura actual en grados Celsius.
                    example: 30
                  recomendacion:
                    type: string
                    description: Recomendación de ropa.
                    example: Ropa muy ligera (camiseta, shorts, ropa de verano)
        '400':
          description: Error al no proporcionar la ciudad
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Por favor, proporcione una ciudad"
        '500':
          description: Error del servidor al obtener los datos meteorológicos
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error al obtener los datos meteorológicos"
